// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // oGameStartControl
global.__objectDepths[1] = -100000; // oGameControl
global.__objectDepths[2] = 0; // oStartMenuControl
global.__objectDepths[3] = 0; // oMapControl
global.__objectDepths[4] = 100000; // oCamera
global.__objectDepths[5] = 0; // oIntControl
global.__objectDepths[6] = 0; // oMapHeightCell
global.__objectDepths[7] = 0; // oPlayerControl
global.__objectDepths[8] = 0; // oAttackControl
global.__objectDepths[9] = 0; // oSpecialAttackControl
global.__objectDepths[10] = 0; // oKnockControl
global.__objectDepths[11] = 0; // oKillControl
global.__objectDepths[12] = -10000; // oAIControl
global.__objectDepths[13] = -100000; // oActionControl
global.__objectDepths[14] = -10000; // oItemControl
global.__objectDepths[15] = 0; // oXPControl
global.__objectDepths[16] = 0; // oAIActivationControl
global.__objectDepths[17] = 0; // oNemesisControl
global.__objectDepths[18] = 0; // oMapCreatorControl
global.__objectDepths[19] = 0; // oTramAnimControl
global.__objectDepths[20] = 0; // oTramInterstitialAnimControl
global.__objectDepths[21] = 0; // oIconControl
global.__objectDepths[22] = -9800; // oLightingControl
global.__objectDepths[23] = 0; // oRelationshipControl
global.__objectDepths[24] = -10000; // oElevatorInterstitialControl
global.__objectDepths[25] = 0; // oRevivalControl
global.__objectDepths[26] = 0; // oDisplayControl
global.__objectDepths[27] = 0; // oKongControl
global.__objectDepths[28] = 0; // oTrickShotControl
global.__objectDepths[29] = 0; // oWaitForMeControl
global.__objectDepths[30] = 0; // oFirstAidControl
global.__objectDepths[31] = -11000; // oToolTipControl
global.__objectDepths[32] = 0; // oSoundControl
global.__objectDepths[33] = 0; // oSoundStopControl
global.__objectDepths[34] = 0; // oIMouseControl
global.__objectDepths[35] = 0; // oUnitParent
global.__objectDepths[36] = 0; // oAuditor
global.__objectDepths[37] = 0; // oPlayerUnitParent
global.__objectDepths[38] = 0; // oEnemyTemplate
global.__objectDepths[39] = 0; // oBWBotTest
global.__objectDepths[40] = 0; // oKineticRobit
global.__objectDepths[41] = 0; // oCabra
global.__objectDepths[42] = 0; // oSawbot
global.__objectDepths[43] = 0; // oDecabra
global.__objectDepths[44] = 0; // oCabracitor
global.__objectDepths[45] = 0; // oSkullsplode
global.__objectDepths[46] = 0; // oElectRobit
global.__objectDepths[47] = 0; // oHoverSpark
global.__objectDepths[48] = 0; // oSpookyRobit
global.__objectDepths[49] = 0; // oNemesisTemplate
global.__objectDepths[50] = 0; // oOsculaNemesis
global.__objectDepths[51] = 0; // oNemesisStandin
global.__objectDepths[52] = 0; // oEnvironmentObjectUnit
global.__objectDepths[53] = 0; // oExplodable
global.__objectDepths[54] = 0; // oGreenBarrel
global.__objectDepths[55] = 0; // oKOAuditor
global.__objectDepths[56] = 0; // oCorpseAuditor
global.__objectDepths[57] = 0; // oCrateParent
global.__objectDepths[58] = 0; // oRedChest
global.__objectDepths[59] = 0; // oCrateStandin
global.__objectDepths[60] = 0; // oItemParent
global.__objectDepths[61] = 0; // oUseItem
global.__objectDepths[62] = 0; // oUseItemStandIn
global.__objectDepths[63] = 0; // oContainerItemStandin
global.__objectDepths[64] = 0; // oMedKitItem
global.__objectDepths[65] = 0; // oGrenadeItem
global.__objectDepths[66] = 0; // oWeaponItemTemplate
global.__objectDepths[67] = 0; // oCrowbarItem
global.__objectDepths[68] = 0; // oTwoByFourItem
global.__objectDepths[69] = 0; // oFireAxeItem
global.__objectDepths[70] = 0; // oNailGunItem
global.__objectDepths[71] = 0; // oHealRayItem
global.__objectDepths[72] = 0; // oSmallRevolverItem
global.__objectDepths[73] = 0; // oShockProdItem
global.__objectDepths[74] = 0; // oLaserSawItem
global.__objectDepths[75] = 0; // oWeldGunItem
global.__objectDepths[76] = 0; // oPlasmaRifleItem
global.__objectDepths[77] = 0; // oStunPistolItem
global.__objectDepths[78] = 0; // oLiveWiresItem
global.__objectDepths[79] = 0; // oCursedbarItem
global.__objectDepths[80] = 0; // oResinChunkItem
global.__objectDepths[81] = 0; // oTentacleWeaponItem
global.__objectDepths[82] = 0; // oRitualKnifeItem
global.__objectDepths[83] = 0; // oCursedCutterItem
global.__objectDepths[84] = 0; // oYoricksMawItem
global.__objectDepths[85] = 0; // oStandInDestroyer
global.__objectDepths[86] = 0; // oMapTestGridTile
global.__objectDepths[87] = 0; // oMapTile
global.__objectDepths[88] = 0; // oCatwalkTile
global.__objectDepths[89] = 0; // oDoorTerminal
global.__objectDepths[90] = 0; // oVendingMachine
global.__objectDepths[91] = 0; // oPitTile
global.__objectDepths[92] = 0; // oElevatorTile
global.__objectDepths[93] = 0; // oDoorTile
global.__objectDepths[94] = 0; // oAllMapTiles
global.__objectDepths[95] = 0; // oObstacle
global.__objectDepths[96] = 0; // oTileDressing
global.__objectDepths[97] = -10000; // oUnitWindow
global.__objectDepths[98] = -10000; // oAttackWindow
global.__objectDepths[99] = -10000; // oContainerWindow
global.__objectDepths[100] = -10000; // oVendorWindow
global.__objectDepths[101] = -10000; // oLevelUpWindow
global.__objectDepths[102] = -10000; // oLearnAbilityWindow
global.__objectDepths[103] = -10000; // oRelationshipUpWindow
global.__objectDepths[104] = 0; // oWindowParent
global.__objectDepths[105] = 0; // oUnitStatsWindow
global.__objectDepths[106] = 0; // oAttackStatParent
global.__objectDepths[107] = 0; // oEnemyHitStatBox
global.__objectDepths[108] = 0; // oEnemyCritStatBox
global.__objectDepths[109] = 0; // oEnemyKnockStatBox
global.__objectDepths[110] = 0; // oEnemyDamStatBox
global.__objectDepths[111] = 0; // oPlayerHitStatBox
global.__objectDepths[112] = 0; // oPlayerHealStatBox
global.__objectDepths[113] = 0; // oPlayerDamStatBox
global.__objectDepths[114] = 0; // oPlayerCritStatBox
global.__objectDepths[115] = 0; // oPlayerKnockStatBox
global.__objectDepths[116] = -10000; // oTramInterstitialInfoWindow
global.__objectDepths[117] = -10000; // oUnitFacingArrowWindow
global.__objectDepths[118] = -10000; // oGenericInfoWindow
global.__objectDepths[119] = 0; // oAbilityLearnButton
global.__objectDepths[120] = -10000; // oKongButton
global.__objectDepths[121] = -10000; // oTrickShotButton
global.__objectDepths[122] = -10000; // oFirstAidButton
global.__objectDepths[123] = -10000; // oSureFootingButton
global.__objectDepths[124] = -10000; // oSprintButton
global.__objectDepths[125] = -10000; // oNimbleButton
global.__objectDepths[126] = -10000; // oLeapButton
global.__objectDepths[127] = -10000; // oCharmerButton
global.__objectDepths[128] = -10000; // oBlendInButton
global.__objectDepths[129] = -10000; // oDiversionButton
global.__objectDepths[130] = -10000; // oReflexesButton
global.__objectDepths[131] = -10000; // oButton
global.__objectDepths[132] = -10000; // oConfirmButton
global.__objectDepths[133] = -10000; // oElevatorButton
global.__objectDepths[134] = -10000; // oCancelButton
global.__objectDepths[135] = -10000; // oAttackShoveButton
global.__objectDepths[136] = -10000; // oTakeNoSwapButton
global.__objectDepths[137] = -10000; // oCancelMoveButton
global.__objectDepths[138] = -10000; // oMoveNextRoomButton
global.__objectDepths[139] = -10000; // oUseDoorTerminalButton
global.__objectDepths[140] = -10000; // oUseVendorButton
global.__objectDepths[141] = -10000; // oPickUpItemButton
global.__objectDepths[142] = -10000; // oDoFacingButton
global.__objectDepths[143] = -10000; // oOpenContainerButton
global.__objectDepths[144] = -10002; // oInventoryButton
global.__objectDepths[145] = -10002; // oItemPurchaseButton
global.__objectDepths[146] = -10005; // oUseTrapItemButton
global.__objectDepths[147] = -10002; // oInventoryInteractButton
global.__objectDepths[148] = -10005; // oUseConsumableItemButton
global.__objectDepths[149] = -10007; // oDiscardItemButton
global.__objectDepths[150] = -10007; // oStoreEquippedItemButton
global.__objectDepths[151] = -10007; // oEquipItemButton
global.__objectDepths[152] = -10007; // oGiveItemButton
global.__objectDepths[153] = -10007; // oCancelItemButton
global.__objectDepths[154] = -10007; // oCancelAbilityButton
global.__objectDepths[155] = -10000; // oHealIcon
global.__objectDepths[156] = -10000; // oAttackIcon
global.__objectDepths[157] = 0; // oStatusIcon
global.__objectDepths[158] = 0; // oIntRedExclamation
global.__objectDepths[159] = -9999; // oUnitFacingArrow
global.__objectDepths[160] = 0; // oAbilityIcon
global.__objectDepths[161] = -10000; // oShockIcon
global.__objectDepths[162] = -10000; // oMissedIcon
global.__objectDepths[163] = -10000; // oCritIcon
global.__objectDepths[164] = 0; // oAbilityUsedIcon
global.__objectDepths[165] = 0; // oMenuParent
global.__objectDepths[166] = -10000; // oPauseMenu
global.__objectDepths[167] = -15000; // oSettingsMenu
global.__objectDepths[168] = 0; // oMenuButtonParent
global.__objectDepths[169] = 0; // oMenuPauseResumeButton
global.__objectDepths[170] = 0; // oMenuPauseQuitButton
global.__objectDepths[171] = 0; // oMenuPauseSettingsButton
global.__objectDepths[172] = -10000; // oMenuSliderParent
global.__objectDepths[173] = -10000; // oMenuSliderEffectsVolume
global.__objectDepths[174] = -10000; // oMenuSettingsAcceptButton
global.__objectDepths[175] = -10000; // oMenuSettingsCancelButton
global.__objectDepths[176] = -10000; // oMenuSettingsFullscreenButton
global.__objectDepths[177] = -10000; // oMenuSettingsWindowedButton
global.__objectDepths[178] = 0; // oTrickShotIndicator
global.__objectDepths[179] = 0; // oClickable
global.__objectDepths[180] = -100000; // oTurnIndicator
global.__objectDepths[181] = -20000; // oUnitActivationView
global.__objectDepths[182] = 0; // oDrawXP
global.__objectDepths[183] = 0; // oUnitAttackCursor
global.__objectDepths[184] = 0; // oUnitSelectCursor
global.__objectDepths[185] = -10000; // oDrawHealHP
global.__objectDepths[186] = -10000; // oDrawAttackHP
global.__objectDepths[187] = 0; // oTileCursorTempDebug
global.__objectDepths[188] = 0; // oTileCursor
global.__objectDepths[189] = 0; // oTileCursorBG
global.__objectDepths[190] = 0; // oKnockRange
global.__objectDepths[191] = 0; // oPreAttackRange
global.__objectDepths[192] = 0; // oMoveRange
global.__objectDepths[193] = 0; // oAttackRange
global.__objectDepths[194] = 0; // oItemRange
global.__objectDepths[195] = -3000; // oExplosionEffect
global.__objectDepths[196] = 0; // oRoomDecorationParent
global.__objectDepths[197] = 0; // oDoorPit
global.__objectDepths[198] = 0; // oTramTerminal
global.__objectDepths[199] = 0; // oLightSource
global.__objectDepths[200] = 10000; // oScrollingWall
global.__objectDepths[201] = 0; // oDebrisParticle
global.__objectDepths[202] = 0; // oParentParticle
global.__objectDepths[203] = 0; // oNailBulletParticle
global.__objectDepths[204] = 0; // oSmallSteamParticle
global.__objectDepths[205] = 0; // oSmallKineticPuffParticle
global.__objectDepths[206] = 0; // oSmallKineticHitParticle
global.__objectDepths[207] = 0; // oSmallPlasmaParticle
global.__objectDepths[208] = 0; // oSmallPlasmaTrailParticle
global.__objectDepths[209] = 0; // oSmallEnergyHitParticle
global.__objectDepths[210] = 0; // oSmallEnergyPuffParticle
global.__objectDepths[211] = 0; // oSmallSkullParticle
global.__objectDepths[212] = 0; // oSmallGreenTrailParticle
global.__objectDepths[213] = 0; // oSmallEldritchHitParticle
global.__objectDepths[214] = 0; // oSmallEldritchPuffParticle
global.__objectDepths[215] = 0; // oHeartTrailParticle
global.__objectDepths[216] = 0; // oHeartParticle
global.__objectDepths[217] = -10000; // oHeartPump
global.__objectDepths[218] = 0; // oHealParticleFirstAid1
global.__objectDepths[219] = 0; // oHealParticleSmall
global.__objectDepths[220] = -10000; // oRotarySawParticle
global.__objectDepths[221] = 0; // oChildOfNoiseTitle
global.__objectDepths[222] = 0; // oChildOfNoiseTitleSave
global.__objectDepths[223] = -10000; // oNewGameButton
global.__objectDepths[224] = -10000; // oTopMenuSettingsButton
global.__objectDepths[225] = -10000; // oTopMenuQuitButton
global.__objectDepths[226] = 0; // oGNoiseGenerator
global.__objectDepths[227] = 0; // oDrawMainMenu
global.__objectDepths[228] = 0; // oMenuPalaceLights3
global.__objectDepths[229] = 0; // oMenuPalaceBGStar
global.__objectDepths[230] = 0; // oMenuPalaceExhaust1
global.__objectDepths[231] = 0; // oMenuPalaceLights4
global.__objectDepths[232] = 0; // oMenuPalaceLights2
global.__objectDepths[233] = 0; // oMenuPalaceLights1


global.__objectNames[0] = "oGameStartControl";
global.__objectNames[1] = "oGameControl";
global.__objectNames[2] = "oStartMenuControl";
global.__objectNames[3] = "oMapControl";
global.__objectNames[4] = "oCamera";
global.__objectNames[5] = "oIntControl";
global.__objectNames[6] = "oMapHeightCell";
global.__objectNames[7] = "oPlayerControl";
global.__objectNames[8] = "oAttackControl";
global.__objectNames[9] = "oSpecialAttackControl";
global.__objectNames[10] = "oKnockControl";
global.__objectNames[11] = "oKillControl";
global.__objectNames[12] = "oAIControl";
global.__objectNames[13] = "oActionControl";
global.__objectNames[14] = "oItemControl";
global.__objectNames[15] = "oXPControl";
global.__objectNames[16] = "oAIActivationControl";
global.__objectNames[17] = "oNemesisControl";
global.__objectNames[18] = "oMapCreatorControl";
global.__objectNames[19] = "oTramAnimControl";
global.__objectNames[20] = "oTramInterstitialAnimControl";
global.__objectNames[21] = "oIconControl";
global.__objectNames[22] = "oLightingControl";
global.__objectNames[23] = "oRelationshipControl";
global.__objectNames[24] = "oElevatorInterstitialControl";
global.__objectNames[25] = "oRevivalControl";
global.__objectNames[26] = "oDisplayControl";
global.__objectNames[27] = "oKongControl";
global.__objectNames[28] = "oTrickShotControl";
global.__objectNames[29] = "oWaitForMeControl";
global.__objectNames[30] = "oFirstAidControl";
global.__objectNames[31] = "oToolTipControl";
global.__objectNames[32] = "oSoundControl";
global.__objectNames[33] = "oSoundStopControl";
global.__objectNames[34] = "oIMouseControl";
global.__objectNames[35] = "oUnitParent";
global.__objectNames[36] = "oAuditor";
global.__objectNames[37] = "oPlayerUnitParent";
global.__objectNames[38] = "oEnemyTemplate";
global.__objectNames[39] = "oBWBotTest";
global.__objectNames[40] = "oKineticRobit";
global.__objectNames[41] = "oCabra";
global.__objectNames[42] = "oSawbot";
global.__objectNames[43] = "oDecabra";
global.__objectNames[44] = "oCabracitor";
global.__objectNames[45] = "oSkullsplode";
global.__objectNames[46] = "oElectRobit";
global.__objectNames[47] = "oHoverSpark";
global.__objectNames[48] = "oSpookyRobit";
global.__objectNames[49] = "oNemesisTemplate";
global.__objectNames[50] = "oOsculaNemesis";
global.__objectNames[51] = "oNemesisStandin";
global.__objectNames[52] = "oEnvironmentObjectUnit";
global.__objectNames[53] = "oExplodable";
global.__objectNames[54] = "oGreenBarrel";
global.__objectNames[55] = "oKOAuditor";
global.__objectNames[56] = "oCorpseAuditor";
global.__objectNames[57] = "oCrateParent";
global.__objectNames[58] = "oRedChest";
global.__objectNames[59] = "oCrateStandin";
global.__objectNames[60] = "oItemParent";
global.__objectNames[61] = "oUseItem";
global.__objectNames[62] = "oUseItemStandIn";
global.__objectNames[63] = "oContainerItemStandin";
global.__objectNames[64] = "oMedKitItem";
global.__objectNames[65] = "oGrenadeItem";
global.__objectNames[66] = "oWeaponItemTemplate";
global.__objectNames[67] = "oCrowbarItem";
global.__objectNames[68] = "oTwoByFourItem";
global.__objectNames[69] = "oFireAxeItem";
global.__objectNames[70] = "oNailGunItem";
global.__objectNames[71] = "oHealRayItem";
global.__objectNames[72] = "oSmallRevolverItem";
global.__objectNames[73] = "oShockProdItem";
global.__objectNames[74] = "oLaserSawItem";
global.__objectNames[75] = "oWeldGunItem";
global.__objectNames[76] = "oPlasmaRifleItem";
global.__objectNames[77] = "oStunPistolItem";
global.__objectNames[78] = "oLiveWiresItem";
global.__objectNames[79] = "oCursedbarItem";
global.__objectNames[80] = "oResinChunkItem";
global.__objectNames[81] = "oTentacleWeaponItem";
global.__objectNames[82] = "oRitualKnifeItem";
global.__objectNames[83] = "oCursedCutterItem";
global.__objectNames[84] = "oYoricksMawItem";
global.__objectNames[85] = "oStandInDestroyer";
global.__objectNames[86] = "oMapTestGridTile";
global.__objectNames[87] = "oMapTile";
global.__objectNames[88] = "oCatwalkTile";
global.__objectNames[89] = "oDoorTerminal";
global.__objectNames[90] = "oVendingMachine";
global.__objectNames[91] = "oPitTile";
global.__objectNames[92] = "oElevatorTile";
global.__objectNames[93] = "oDoorTile";
global.__objectNames[94] = "oAllMapTiles";
global.__objectNames[95] = "oObstacle";
global.__objectNames[96] = "oTileDressing";
global.__objectNames[97] = "oUnitWindow";
global.__objectNames[98] = "oAttackWindow";
global.__objectNames[99] = "oContainerWindow";
global.__objectNames[100] = "oVendorWindow";
global.__objectNames[101] = "oLevelUpWindow";
global.__objectNames[102] = "oLearnAbilityWindow";
global.__objectNames[103] = "oRelationshipUpWindow";
global.__objectNames[104] = "oWindowParent";
global.__objectNames[105] = "oUnitStatsWindow";
global.__objectNames[106] = "oAttackStatParent";
global.__objectNames[107] = "oEnemyHitStatBox";
global.__objectNames[108] = "oEnemyCritStatBox";
global.__objectNames[109] = "oEnemyKnockStatBox";
global.__objectNames[110] = "oEnemyDamStatBox";
global.__objectNames[111] = "oPlayerHitStatBox";
global.__objectNames[112] = "oPlayerHealStatBox";
global.__objectNames[113] = "oPlayerDamStatBox";
global.__objectNames[114] = "oPlayerCritStatBox";
global.__objectNames[115] = "oPlayerKnockStatBox";
global.__objectNames[116] = "oTramInterstitialInfoWindow";
global.__objectNames[117] = "oUnitFacingArrowWindow";
global.__objectNames[118] = "oGenericInfoWindow";
global.__objectNames[119] = "oAbilityLearnButton";
global.__objectNames[120] = "oKongButton";
global.__objectNames[121] = "oTrickShotButton";
global.__objectNames[122] = "oFirstAidButton";
global.__objectNames[123] = "oSureFootingButton";
global.__objectNames[124] = "oSprintButton";
global.__objectNames[125] = "oNimbleButton";
global.__objectNames[126] = "oLeapButton";
global.__objectNames[127] = "oCharmerButton";
global.__objectNames[128] = "oBlendInButton";
global.__objectNames[129] = "oDiversionButton";
global.__objectNames[130] = "oReflexesButton";
global.__objectNames[131] = "oButton";
global.__objectNames[132] = "oConfirmButton";
global.__objectNames[133] = "oElevatorButton";
global.__objectNames[134] = "oCancelButton";
global.__objectNames[135] = "oAttackShoveButton";
global.__objectNames[136] = "oTakeNoSwapButton";
global.__objectNames[137] = "oCancelMoveButton";
global.__objectNames[138] = "oMoveNextRoomButton";
global.__objectNames[139] = "oUseDoorTerminalButton";
global.__objectNames[140] = "oUseVendorButton";
global.__objectNames[141] = "oPickUpItemButton";
global.__objectNames[142] = "oDoFacingButton";
global.__objectNames[143] = "oOpenContainerButton";
global.__objectNames[144] = "oInventoryButton";
global.__objectNames[145] = "oItemPurchaseButton";
global.__objectNames[146] = "oUseTrapItemButton";
global.__objectNames[147] = "oInventoryInteractButton";
global.__objectNames[148] = "oUseConsumableItemButton";
global.__objectNames[149] = "oDiscardItemButton";
global.__objectNames[150] = "oStoreEquippedItemButton";
global.__objectNames[151] = "oEquipItemButton";
global.__objectNames[152] = "oGiveItemButton";
global.__objectNames[153] = "oCancelItemButton";
global.__objectNames[154] = "oCancelAbilityButton";
global.__objectNames[155] = "oHealIcon";
global.__objectNames[156] = "oAttackIcon";
global.__objectNames[157] = "oStatusIcon";
global.__objectNames[158] = "oIntRedExclamation";
global.__objectNames[159] = "oUnitFacingArrow";
global.__objectNames[160] = "oAbilityIcon";
global.__objectNames[161] = "oShockIcon";
global.__objectNames[162] = "oMissedIcon";
global.__objectNames[163] = "oCritIcon";
global.__objectNames[164] = "oAbilityUsedIcon";
global.__objectNames[165] = "oMenuParent";
global.__objectNames[166] = "oPauseMenu";
global.__objectNames[167] = "oSettingsMenu";
global.__objectNames[168] = "oMenuButtonParent";
global.__objectNames[169] = "oMenuPauseResumeButton";
global.__objectNames[170] = "oMenuPauseQuitButton";
global.__objectNames[171] = "oMenuPauseSettingsButton";
global.__objectNames[172] = "oMenuSliderParent";
global.__objectNames[173] = "oMenuSliderEffectsVolume";
global.__objectNames[174] = "oMenuSettingsAcceptButton";
global.__objectNames[175] = "oMenuSettingsCancelButton";
global.__objectNames[176] = "oMenuSettingsFullscreenButton";
global.__objectNames[177] = "oMenuSettingsWindowedButton";
global.__objectNames[178] = "oTrickShotIndicator";
global.__objectNames[179] = "oClickable";
global.__objectNames[180] = "oTurnIndicator";
global.__objectNames[181] = "oUnitActivationView";
global.__objectNames[182] = "oDrawXP";
global.__objectNames[183] = "oUnitAttackCursor";
global.__objectNames[184] = "oUnitSelectCursor";
global.__objectNames[185] = "oDrawHealHP";
global.__objectNames[186] = "oDrawAttackHP";
global.__objectNames[187] = "oTileCursorTempDebug";
global.__objectNames[188] = "oTileCursor";
global.__objectNames[189] = "oTileCursorBG";
global.__objectNames[190] = "oKnockRange";
global.__objectNames[191] = "oPreAttackRange";
global.__objectNames[192] = "oMoveRange";
global.__objectNames[193] = "oAttackRange";
global.__objectNames[194] = "oItemRange";
global.__objectNames[195] = "oExplosionEffect";
global.__objectNames[196] = "oRoomDecorationParent";
global.__objectNames[197] = "oDoorPit";
global.__objectNames[198] = "oTramTerminal";
global.__objectNames[199] = "oLightSource";
global.__objectNames[200] = "oScrollingWall";
global.__objectNames[201] = "oDebrisParticle";
global.__objectNames[202] = "oParentParticle";
global.__objectNames[203] = "oNailBulletParticle";
global.__objectNames[204] = "oSmallSteamParticle";
global.__objectNames[205] = "oSmallKineticPuffParticle";
global.__objectNames[206] = "oSmallKineticHitParticle";
global.__objectNames[207] = "oSmallPlasmaParticle";
global.__objectNames[208] = "oSmallPlasmaTrailParticle";
global.__objectNames[209] = "oSmallEnergyHitParticle";
global.__objectNames[210] = "oSmallEnergyPuffParticle";
global.__objectNames[211] = "oSmallSkullParticle";
global.__objectNames[212] = "oSmallGreenTrailParticle";
global.__objectNames[213] = "oSmallEldritchHitParticle";
global.__objectNames[214] = "oSmallEldritchPuffParticle";
global.__objectNames[215] = "oHeartTrailParticle";
global.__objectNames[216] = "oHeartParticle";
global.__objectNames[217] = "oHeartPump";
global.__objectNames[218] = "oHealParticleFirstAid1";
global.__objectNames[219] = "oHealParticleSmall";
global.__objectNames[220] = "oRotarySawParticle";
global.__objectNames[221] = "oChildOfNoiseTitle";
global.__objectNames[222] = "oChildOfNoiseTitleSave";
global.__objectNames[223] = "oNewGameButton";
global.__objectNames[224] = "oTopMenuSettingsButton";
global.__objectNames[225] = "oTopMenuQuitButton";
global.__objectNames[226] = "oGNoiseGenerator";
global.__objectNames[227] = "oDrawMainMenu";
global.__objectNames[228] = "oMenuPalaceLights3";
global.__objectNames[229] = "oMenuPalaceBGStar";
global.__objectNames[230] = "oMenuPalaceExhaust1";
global.__objectNames[231] = "oMenuPalaceLights4";
global.__objectNames[232] = "oMenuPalaceLights2";
global.__objectNames[233] = "oMenuPalaceLights1";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for