/// @description sMakeAuditorNameList()
/*this script makes lists of "male" and "female" names to be drawn on from the creation
script. Names, like gender, are strictly cosmetic.
*/
mnamelist = ds_list_create()

ds_list_add(mnamelist,"John")
ds_list_add(mnamelist,"Jon")
ds_list_add(mnamelist,"Christoph")
ds_list_add(mnamelist,"Bob")
ds_list_add(mnamelist,"Hendrick")
ds_list_add(mnamelist,"Zalbador")
ds_list_add(mnamelist,"Alden")
ds_list_add(mnamelist,"Ted")
ds_list_add(mnamelist,"Justin")
ds_list_add(mnamelist,"Hans")
ds_list_add(mnamelist,"Tyrol")
ds_list_add(mnamelist,"Terry")
ds_list_add(mnamelist,"Danny")
ds_list_add(mnamelist,"Yunru")
ds_list_add(mnamelist,"Erol")
ds_list_add(mnamelist,"Fjord")
ds_list_add(mnamelist,"Shia")
ds_list_add(mnamelist,"Hwan")
ds_list_add(mnamelist,"Shirong")
ds_list_add(mnamelist,"Issac")
ds_list_add(mnamelist,"Abel")
ds_list_add(mnamelist,"Steve")
ds_list_add(mnamelist,"Jingguo")
ds_list_add(mnamelist,"Guillermo")
ds_list_add(mnamelist,"Kwan")
ds_list_add(mnamelist,"Dick")
ds_list_add(mnamelist,"Don")
ds_list_add(mnamelist,"Yoseph")
ds_list_add(mnamelist,"Pablo")
ds_list_add(mnamelist,"Sufjan")
ds_list_add(mnamelist,"Jose")
ds_list_add(mnamelist,"Pedro")
ds_list_add(mnamelist,"Ben")
ds_list_add(mnamelist,"Donny")
ds_list_add(mnamelist,"Tengfei")
ds_list_add(mnamelist,"Narciso")
ds_list_add(mnamelist,"Nick")
ds_list_add(mnamelist,"Willy")
ds_list_add(mnamelist,"Eloy")
ds_list_add(mnamelist,"Tunde")
ds_list_add(mnamelist,"Daquan")
ds_list_add(mnamelist,"Kipp")
ds_list_add(mnamelist,"Jaleel")
ds_list_add(mnamelist,"David")
ds_list_add(mnamelist,"Ludovic")
ds_list_add(mnamelist,"Fernando")
ds_list_add(mnamelist,"Bellamy")
ds_list_add(mnamelist,"Jessie")
ds_list_add(mnamelist,"Jerome")
ds_list_add(mnamelist,"Kenny")
ds_list_add(mnamelist,"Hannibal")
ds_list_add(mnamelist,"Langston")
ds_list_add(mnamelist,"Alingon")
ds_list_add(mnamelist,"Bayan")
ds_list_add(mnamelist,"Damien")
ds_list_add(mnamelist,"Jordan")
ds_list_add(mnamelist,"Esco")
ds_list_add(mnamelist,"Diego")
ds_list_add(mnamelist,"Cheng")
ds_list_add(mnamelist,"Miguel")
ds_list_add(mnamelist,"Duncan")


fnamelist = ds_list_create()

ds_list_add(fnamelist,"Corie")
ds_list_add(fnamelist,"Janice")
ds_list_add(fnamelist,"Leslie")
ds_list_add(fnamelist,"Faye")
ds_list_add(fnamelist,"Wednesday")
ds_list_add(fnamelist,"April")
ds_list_add(fnamelist,"Astaire")
ds_list_add(fnamelist,"Alice")
ds_list_add(fnamelist,"Shandra")
ds_list_add(fnamelist,"Juanita")
ds_list_add(fnamelist,"Giselle")
ds_list_add(fnamelist,"Sung")
ds_list_add(fnamelist,"Isabella")
ds_list_add(fnamelist,"Lessa")
ds_list_add(fnamelist,"Becky")
ds_list_add(fnamelist,"Gertrude")
ds_list_add(fnamelist,"Anahera")
ds_list_add(fnamelist,"Moana")
ds_list_add(fnamelist,"Yoshime")
ds_list_add(fnamelist,"Aoki")
ds_list_add(fnamelist,"Bellanie")
ds_list_add(fnamelist,"Dolly")
ds_list_add(fnamelist,"Nari")
ds_list_add(fnamelist,"Tally")
ds_list_add(fnamelist,"Annette")
ds_list_add(fnamelist,"Zhilan")
ds_list_add(fnamelist,"Chris")
ds_list_add(fnamelist,"Hillary")
ds_list_add(fnamelist,"Florence")
ds_list_add(fnamelist,"Huiling")
ds_list_add(fnamelist,"Areum")
ds_list_add(fnamelist,"Soledad")
ds_list_add(fnamelist,"Emily")
ds_list_add(fnamelist,"Araceli")
ds_list_add(fnamelist,"Yoko")
ds_list_add(fnamelist,"Noko")
ds_list_add(fnamelist,"Moko")
ds_list_add(fnamelist,"Liling")
ds_list_add(fnamelist,"Yolanda")
ds_list_add(fnamelist,"Kara")
ds_list_add(fnamelist,"River")
ds_list_add(fnamelist,"Xiaofan")
ds_list_add(fnamelist,"Jasana")
ds_list_add(fnamelist,"Fa")
ds_list_add(fnamelist,"Biyu")
ds_list_add(fnamelist,"Jasmine")
ds_list_add(fnamelist,"Donna")
ds_list_add(fnamelist,"Djohariah")
ds_list_add(fnamelist,"Hye")
ds_list_add(fnamelist,"Phoebe")
ds_list_add(fnamelist,"Jessica")
ds_list_add(fnamelist,"Nicole")
ds_list_add(fnamelist,"Ilana")
ds_list_add(fnamelist,"Sasheer")
ds_list_add(fnamelist,"Sasha")
ds_list_add(fnamelist,"Nadya")
ds_list_add(fnamelist,"Ayanna")
ds_list_add(fnamelist,"Hadiyah")
ds_list_add(fnamelist,"Selma")
ds_list_add(fnamelist,"Frida")
ds_list_add(fnamelist,"Jessa")
ds_list_add(fnamelist,"Yersa")



ds_list_shuffle(fnamelist)
ds_list_shuffle(mnamelist)





